const MODES = {
  eleve: {
    key: "eleve",
    routeSegment: "eleves",
    apiRoute: "POST /eleves/import",
    title: "Import des élèves",
    subtitle: "Chaque ligne crée un compte utilisateur et une inscription pour l'année académique active.",
    badge: "Élèves",
    cardTitle: "Importer des élèves",
    importLabel: "élèves",
    needsClass: true,
    columns: [
      { key: "matricule",     label: "Matricule",     required: true  },
      { key: "nom",           label: "Nom",           required: true  },
      { key: "prenom",        label: "Prénom",        required: true  },
      { key: "dateNaissance", label: "dateNaissance", required: false },
      { key: "lieuNaissance", label: "lieuNaissance", required: false },
      { key: "sexe",          label: "Sexe",          required: false },
      { key: "affecte",       label: "Affecté",       required: false },
      { key: "boursier",      label: "Boursier",      required: false },
      { key: "redoublant",    label: "Redoublant",    required: false },
      { key: "nationalite",   label: "Nationalité",   required: false },
    ],
    accent: "#2563eb",
    accentLight: "#eff6ff",
    accentBorder: "#bfdbfe",
    accentText: "#1d4ed8",
  },
  enseignant: {
    key: "enseignant",
    routeSegment: "enseignants",
    apiRoute: "POST /enseignants/create",
    title: "Import des enseignants",
    subtitle: "Chaque ligne crée un compte enseignant rattaché automatiquement à votre établissement.",
    badge: "Enseignants",
    cardTitle: "Importer des enseignants",
    importLabel: "enseignants",
    needsClass: false,
    columns: [
      { key: "matricule", label: "Matricule", required: true },
      { key: "nom",       label: "Nom",       required: true },
      { key: "prenom",    label: "Prénom",    required: true },
    ],
    accent: "#7c3aed",
    accentLight: "#f5f3ff",
    accentBorder: "#ddd6fe",
    accentText: "#6d28d9",
  },
};

export default MODES